spring:
  redis:
    host: localhost
    port: 6379
    database: 0
  cloud:
    gateway:
      routes:
        - id: route1
          uri: lb://consumer-service/
          predicates:
            - Path=/gat/**
          #            - Method=POST
          #            - Cookie=name,zhangsan
          #            - Header=role,admin
          #            - Query=pageNum,\d+
          filters:
            - StripPrefix=1
            #filters名称必须是RequestRateLimiter
            - name: RequestRateLimiter
              args:
                #使用SpEL按名称引用bean
                key-resolver: "#{@remoteAddrKeyResolver}"
                #请允用户每秒钟处理多少个请求
                redis-rate-limiter.replenishRate: 10
                #令牌桶的容量，允许每秒钟内完成的最大的请求数
                redis-rate-limiter.burshCapacity: 20
